




def PythonBasicsI():


    baihat = '\t \'Mot con vit\' xoe ra 2 cai canh \n No keu rang cap cap cap cap cap cap'
    print(baihat)


    # birth_year = input('What year were you born? ')
    # age = 2022 - int(birth_year)
    # print(f'\n Your age is {age}')

    # # Password checker excercise

    # user_name = input('User name: ')
    # password = input('Password: ')
    # x = len(password)
    # print(type(x))

    # print(f'{user_name}, your password ' + '*'*len(password) + f' is {len(password)} letters long.')


    # # List excercise
    # basket = ["Banana", "Apples", "Oranges", "Blueberries"];

    # # 1. Remove the Banana from the list
    # basket.remove('Banana')
    # print(basket)
    # # 2. Remove "Blueberries" from the list.
    # basket.remove('Blueberries')
    # print(basket)
    # # 3. Put "Kiwi" at the end of the list.
    # basket.append('Kiwi')
    # print(basket)
    # # 4. Add "Apples" at the beginning of the list
    # basket.insert(0,'Apples')
    # print(basket)
    # # 5. Count how many apples in the basket
    # print(basket.count('Apples'))
    # # 6. empty the basket
    # basket.clear()
    # print(basket)


    # #fix this code so that it prints a sorted list of all of our friends (alphabetical). Scroll to see answer
    # friends = ['Simon', 'Patty', 'Joy', 'Carrie', 'Amira', 'Chu']

    # new_friend = ['Stanley']
    # friends += new_friend

    # print(sorted(friends))




    # #dictionary excercise
    # #Scroll down to see the answers!
    # #1 Create a user profile for your new game. This user profile will be stored in a dictionary with keys: 'age', 'username', 'weapons', 'is_active' and 'clan'
    # user = {
    #   'age' : 25,
    #   'username' : 'Trieuvy',
    #   'weapons' : ['keyboard'],
    #   'is_active' : True,
    #   'clan' : 'devine'
    # }


    # #2 iterate and print all the keys in the above user.
    # print(user.keys())

    # #3 Add a new weapon to your user
    # user['weapons'].append('knife')

    # #4 Add a new key to include 'is_banned'. Set it to false
    # user.update(is_banned = False)
    # #5 Ban the user by setting the previous key to True
    # user.update(is_banned = True)

    # #6 create a new user2 my copying the previous user and update the age value and username value.
    # user2 = user.copy()
    # user2.update(username='Nghia', age = 57)
    # print(user)
    # print(user2)


    # Set Excercise
    #Scroll to bottom to see solution
    # You are working for the school Principal. We have a database of school students:
    school = {'Bobby','Tammy','Jammy','Sally','Danny'}

    #during class, the teachers take attendance and compile it into a list.
    attendance_list = ['Jammy', 'Bobby', 'Danny', 'Sally']


    #using what you learned about sets, create a piece of code that the school principal can use to immediately find out who missed class so they can call the parents. (Imagine if the list had 1000s of students. The principal can use the lists generated by the teachers + the school database to use python and make his/her job easier): Find the students that miss class!
    attendance_set = set(attendance_list)
    absend_list = school.difference(attendance_set)
    print(absend_list)

PythonBasicsI()

